name: Check lints and formatting

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: read-all
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4
      - name: Get ruff
        uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format --check
