name: Check lints and formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all
jobs:
  ruff:
    runs-on: ${{ matrix.os }}
    stragegy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Get repo
        uses: actions/checkout@v4
      - name: Get ruff
        uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format --check
